remove -debug from build instructions
ninjamuffin99/Funkin pull request #1350
Opened 2021-07-07 11:21 UTC by lolicop123

because it doesnt create a "release" folder under export, and fucks shit up

when ran with the -debug flag, it creates a /export/debug folder instead of /export/release, and when you go into a level theres a bunch of debug shit on screen lmao
![image](https://user-images.githubusercontent.com/24574201/124750798-cc537800-df1d-11eb-9168-899aa5427e4a.png)

2021-07-09 05:47 UTC, theblobscp approved these changes
Looks fine

2021-07-11 16:07 UTC, ACardboardBox1 commented
i use lime test windows -debug alot and it isnt till now when i found out you could disable it using lime test windows -release

why am i omega dumbass

2021-07-14 03:00 UTC, nickpythonluajava commented
dont use -debug if you don't have to... debug

2021-07-14 03:00 UTC, nickpythonluajava approved these changes

2021-07-21 08:44 UTC, Steviegt6 requested changes
This isn't at all useful as it stands. You misunderstand the purpose of debugging. It'd be better if you specified the differences and elaborated on when to use a debug build or a release build.
The debug stuff isn't random, either, it gives some value information if you were actually working on the game or a mod.

2021-07-21 08:44 UTC, Steviegt6 requested changes

2021-07-21 08:44 UTC, Steviegt6 commented on README.md
>  As for Mac, 'lime test mac -debug' should work, if not the internet surely has a guide on how to compile Haxe stuff for Mac.
You would also need to change this line, by the way.

2021-07-21 16:24 UTC, theblobscp commented
I made a pr on your repo that removes the other -debug stuff

2021-07-21 18:23 UTC, lolicop123 commented
> This isn't at all useful as it stands. You misunderstand the purpose of debugging. It'd be better if you specified the differences and elaborated on when to use a debug build or a release build.
> The debug stuff isn't random, either, it gives some value information if you were actually working on the game or a mod.

good point, ill change it to reflect this once i have some free time

2021-07-22 00:09 UTC, Steviegt6 requested changes

2021-07-22 00:09 UTC, Steviegt6 commented on README.md
> +This will install about 22GB of crap, but once that is done you can open up a command line in the project's directory and run `lime test windows`. If oyu need debug tools, run `lime test windows -deb
Type: "oyu" should be "you".

2021-07-22 00:10 UTC, Steviegt6 commented
> 
> 
> > This isn't at all useful as it stands. You misunderstand the purpose of debugging. It'd be better if you specified the differences and elaborated on when to use a debug build or a release build.
> > The debug stuff isn't random, either, it gives some value information if you were actually working on the game or a mod.
> 
> good point, ill change it to reflect this once i have some free time
> edit: if theres anything else that needs adding, let me know :)

All looks good now, save for a single typo that I pointed out above.

2021-07-22 06:08 UTC, lolicop123 commented
> > > This isn't at all useful as it stands. You misunderstand the purpose of debugging. It'd be better if you specified the differences and elaborated on when to use a debug build or a release build.
> > > The debug stuff isn't random, either, it gives some value information if you were actually working on the game or a mod.
> > 
> > 
> > good point, ill change it to reflect this once i have some free time
> > edit: if theres anything else that needs adding, let me know :)
> 
> All looks good now, save for a single typo that I pointed out above.

thank you :) i cant believe i missed that haha

2021-07-22 14:55 UTC, Steviegt6 approved these changes

2021-08-20 14:54 UTC, closed without merging

2021-08-20 14:54 UTC, ninjamuffin99 commented
nah

2021-08-20 15:22 UTC, lolicop123 commented
> nah

y lol

2021-08-20 21:34 UTC, AbnormalPoof commented
> nah
..yah?