Build workflow so you can build your favorite game in GitHub Actions
ninjamuffin99/Funkin pull request #1765
Opened 2021-09-18 20:45 UTC by theblobscp

Sorry if it breaks, kinda WIP

2021-09-21 00:52 UTC, AbnormalPoof approved these changes
How come nobody seen this

2021-09-26 08:08 UTC, ThePlank approved these changes
I have came back from the dead! Just to approve this pull request.

2021-09-26 13:24 UTC, theblobscp commented
About time old timer

2021-09-30 16:03 UTC, Steviegt6 requested changes
Might also be worthwhile to make Release and Debug builds?

2021-09-30 16:03 UTC, Steviegt6 commented on .github/workflows/build.yml
> +        run: haxelib run lime test mac
This should be `haxelib run lime build mac` since we only care if it builds without issues, we don't perform any unit testing.

2021-09-30 16:03 UTC, Steviegt6 commented on .github/workflows/build.yml
> +        run: haxelib run lime test linux
This should be `haxelib run lime build linux` since we only care if it builds without issues, we don't perform any unit testing.

2021-09-30 16:03 UTC, Steviegt6 commented on .github/workflows/build.yml
> +        run: haxelib run lime test windows
This should be `haxelib run lime build windows` since we only care if it builds without issues, we don't perform any unit testing.

2021-10-01 00:38 UTC, theblobscp commented
@Steviegt6  I fixed it, anything else?

2021-10-01 15:51 UTC, Steviegt6 commented
> @Steviegt6 I fixed it, anything else?

Looks good, thanks.

2021-10-01 15:51 UTC, Steviegt6 approved these changes

2022-06-26 13:04 UTC, theblobscp commented
Closed in favor of #2003.

2022-06-26 13:04 UTC, closed without merging