tankman_assets
ninjamuffin99/Funkin pull request #639
Opened 2021-03-24 00:11 UTC by alejoard6767

tank man assest

2021-03-24 00:18 UTC, alejoard6767 commented on tankman_assets
> +https://www.mediafire.com/file/xqqydl8vyuzlnwg/Tankman_assets.fla/file
this is the tank man assets

2021-03-24 01:03 UTC, TentaRJ commented
Why do you want to add this?

2021-03-24 01:25 UTC, JJ-GRAVITY commented
> Why do you want to add this?

Maybe it's almost time to release week 7.

2021-03-24 04:52 UTC, CaptainGame17 commented
this pr shouldnt exist

2021-03-24 08:18 UTC, Riteo commented
what

2021-03-24 10:07 UTC, The-SGPT commented
this shouldn't even exist cos an fla is already made, just not pushed yet

2021-03-24 20:26 UTC, exurd commented
works on flash professional cs5.5 so it's worthy for a merge-y ;))

![tankmansworld](https://user-images.githubusercontent.com/7785022/112378535-f5d5f400-8cde-11eb-86a6-839993773c74.png)

2021-03-24 20:37 UTC, alejoard6767 commented
tanks to everyone what see the file (you get it?)

2021-03-24 20:39 UTC, alejoard6767 commented on tankman_assets
> +https://www.mediafire.com/file/xqqydl8vyuzlnwg/Tankman_assets.fla/file
tanks to everyone  who see the file (you get it?)

2021-03-24 20:41 UTC, alejoard6767 commented
@exurd  thanks for send a screenshot now i know that work´s

2021-03-24 20:42 UTC, exurd commented
> @exurd thanks for send a screenshot now i know that work´s

/j

2021-03-24 20:42 UTC, alejoard6767 commented
if you do an animation of that please give credit but noting more (sorry for bad english)

2021-03-24 20:44 UTC, alejoard6767 commented
@TentaRJ  im waiting for it

2021-03-24 20:46 UTC, alejoard6767 commented on tankman_assets
> +https://www.mediafire.com/file/xqqydl8vyuzlnwg/Tankman_assets.fla/file
ATENTION IM GONNA TO UPDATE THE FILE TO PUT THE ICONS OF TANKMAN

2021-03-24 20:52 UTC, TentaRJ commented
> @TentaRJ im waiting for it

Good. Wait longer without pinging me next time, alright?

2021-03-24 20:54 UTC, alejoard6767 commented on tankman_assets
> +https://www.mediafire.com/file/xqqydl8vyuzlnwg/Tankman_assets.fla/file
https://www.mediafire.com/file/ewhqot044idj8h7/Tankman_assets.fla/file New tankman files

2021-03-24 20:56 UTC, alejoard6767 commented
ok

2021-03-24 21:47 UTC, alejoard6767 commented
@exurd  you can put more screenshots? please just to see if work´s good

2021-03-24 22:01 UTC, alejoard6767 commented
why no one is chating??

2021-03-25 19:25 UTC, CaptainGame17 commented
> why no one is chating??

this isnt discord lol

2021-03-26 00:51 UTC, alejoard6767 commented
oh sorry

2021-03-26 01:31 UTC, alejoard6767 commented
please someone can send images of the file? just to see if work

2021-03-26 16:01 UTC, TentaRJ requested changes
Don't push this. It doesn't need to be pushed. Please close the request.

2021-03-26 17:35 UTC, alejoard6767 commented on tankman_assets
> +https://www.mediafire.com/file/xqqydl8vyuzlnwg/Tankman_assets.fla/file
i cant sent it directly

2021-03-26 17:36 UTC, hdboye commented
please close this pr. pull requests here are for fixes or improvements to the code. not to add assets which are still being worked on

2021-03-26 17:37 UTC, alejoard6767 commented
im not gonna to close the recuest i worked on the file and in type in english im not english i talk spanish

2021-03-26 17:39 UTC, alejoard6767 commented
and i dont know how to close it

2021-03-26 17:39 UTC, hdboye commented
the fnf team is working on week 7 themselves, they have the assets already. all of these files will eventually be uploaded to the github once week 7 releases.

2021-03-26 17:39 UTC, hdboye commented
> and i dont know how to close it

to the left of the comment button, click Close Pull Request

2021-03-26 17:39 UTC, closed without merging

2021-03-26 17:40 UTC, hdboye commented
thank you

2021-04-06 23:05 UTC, alejoard6767 commented
sorry

El vie, 26 mar 2021 a las 14:39, hd ***@***.***>) escribió:

> the fnf team is working on week 7 themselves, they have the assets
> already. all of these files will eventually be uploaded to the github once
> week 7 releases.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ninjamuffin99/Funkin/pull/639#issuecomment-808402076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMBQIM6XNDCVPCWEK3HLODTFTBEVANCNFSM4ZWGPXFQ>
> .
>