Create APIStuff.hx
ninjamuffin99/Funkin pull request #979
Opened 2021-04-29 16:14 UTC by gingerphoenix10

Fixed the missing file

2021-04-29 19:15 UTC, actuallyasmartname commented
`I gitignore the API keys for the game, so that no one can nab them and post fake highscores on the leaderboards. But because of that the game doesn't compile without it.`
Yeah this won't be merged

2021-05-03 11:04 UTC, Jung-Sun-Kyo commented
만약 여기 깃허브에서 한국에서 사용하는 유저가 있으면 [https://moneyonmymind.tistory.com/245](url)
여기 링크에서 프라이데이 나이트 펌킨을 다운로드 받을 수 있습니다.

2021-05-03 13:15 UTC, notdonxd commented
> 만약 여기 깃허브에서 한국에서 사용하는 유저가 있으면 [https://moneyonmymind.tistory.com/245](url)
> 여기 링크에서 프라이데이 나이트 펌킨을 다운로드 받을 수 있습니다.

what the fuck

2021-05-03 13:18 UTC, VMGuy23 commented
Saying to korean (i think) people where they can get the game

2021-05-05 15:25 UTC, TheDrawingCoder-Gamer commented
:hueh: it's probably a fake link

2021-05-06 17:51 UTC, TentaRJ commented
@gingerphoenix10 
please close this pr. it shouldn't be open.

2021-05-08 15:55 UTC, nickpythonluajava commented
> 만약 여기 깃허브에서 한국에서 사용하는 유저가 있으면 [https://moneyonmymind.tistory.com/245](url)
> 
> 여기 링크에서 프라이데이 나이트 펌킨을 다운로드 받을 수 있습니다.

google translate says:

> If there is a user here in Korea on GitHub, [https://moneyonmymind.tistory.com/245](url)
 >
 > You can download Friday Night Pumpkin from the link here.

2021-05-08 17:07 UTC, VMGuy23 commented
Microsoft Translator says:
> If there are any users used in Korea by GitHub here, https://moneyonmymind.tistory.com/245
> 
> You can download Friday Night Pumpkins from the link here.

2021-05-08 18:50 UTC, nickpythonluajava commented
> Microsoft Translator says:
> 
> > If there are any users used in Korea by GitHub here, https://moneyonmymind.tistory.com/245
> 
> > 
> 
> > You can download Friday Night Pumpkins from the link here.

eh technically same thing

2021-05-11 15:39 UTC, Steviegt6 requested changes
Useless PR. Reasons stated by other comments before this. Just close, kthxbai.

2021-05-14 21:25 UTC, closed without merging